// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idgshimtrxxeqthraryn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkZ3NoaW10cnh4ZXF0aHJhcnluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjEzOTYsImV4cCI6MjA2MDM5NzM5Nn0.YmWELl8oLOLf8z3PGL6fYGesfegWQOOHknySvKmvAec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);